solrUrl: http://localhost:8983/solr
solrCollection: ogp

minPoolSize: 6
maxPoolSize: 12
queueCapacity: 100

connectionPool:
  maxTotal: 100
  maxPerRoute: 10

# maximum memory for the initial ImageBuffer in the ImageCompositor in MB's
# this will be an uncompressed array of ints representing pixels.  To composite,
# the compositor will need about twice this amount of heap space.
# 20 MB roughly equates to an image of 2289 pixels sq.
maxImageSize: 20

# every ${cleanupInterval} milliseconds, files older than ${maxFileAge} minutes are
# deleted from the download folder java.temp/${downloadDir}
downloadDir: ogpdownload
cleanupInterval: 30000
maxFileAge: 240

styleSheet:
  fgdc: WEB-INF/xml/FGDC_V2_a.xsl
  iso19139: WEB-INF/xml/isoBasic.xsl