//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 01:01:16 PM EDT 
//
@javax.xml.bind.annotation.XmlSchema( 
		namespace = "http://www.opengis.net/context",
		location = "http://schemas.opengis.net/context/1.1.0/context.xsd",
	xmlns = {
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.opengis.net/context", prefix = "wmc"),  
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.opengis.net/gml", prefix = "gml"),  
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.opengis.net/ogc", prefix = "ogc"),  
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.opengis.net/sld", prefix = "sld"),
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi"),  
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/1999/xlink", prefix = "xlink")  
		}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opengeoportal.ogc.wmc.jaxb;
