//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.02 at 04:08:12 PM EDT 
//

@XmlSchema(
	namespace = "http://www.opengis.net/context", 
	elementFormDefault = XmlNsForm.QUALIFIED,
	xmlns = {
		@XmlNs(prefix = "", namespaceURI = "http://www.opengis.net/context"),  
		@XmlNs(prefix = "xlink", namespaceURI = "http://www.w3.org/1999/xlink"),
		@XmlNs(prefix = "sld", namespaceURI = "http://www.opengis.net/sld"),  
		@XmlNs(prefix = "gml", namespaceURI = "http://www.opengis.net/gml"), 
		@XmlNs(prefix = "ogc", namespaceURI = "http://www.opengis.net/ogc"),  
		@XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance"),  
		},
		location = "http://schemas.opengis.net/context/1.1.0/context.xsd"
	)
package org.opengeoportal.ogc.wmc.jaxb;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;
import javax.xml.bind.annotation.XmlNsForm;